Fix an issue which observed when using with Streaming Integrator
When using with Streaming integrator NoClassDefFoundError will thrown due to missing of org.apache.commons.csv.CSVFormat class